$primary_paletteKeyColor = ae6257
$secondary_paletteKeyColor = 956d67
$tertiary_paletteKeyColor = baa954
$neutral_paletteKeyColor = 807573
$neutral_variant_paletteKeyColor = 867370
$background = 181211
$onBackground = eedfdd
$surface = 181211
$surfaceDim = 181211
$surfaceBright = 403736
$surfaceContainerLowest = 130d0c
$surfaceContainerLow = 211a19
$surfaceContainer = 251e1d
$surfaceContainerHigh = 302827
$surfaceContainerHighest = 3b3332
$onSurface = eedfdd
$surfaceVariant = 534340
$onSurfaceVariant = d9c1be
$inverseSurface = eedfdd
$inverseOnSurface = 372f2d
$outline = a18c89
$outlineVariant = 534340
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb4a8
$primary = ffb4a8
$onPrimary = 571e16
$primaryContainer = e89285
$onPrimaryContainer = 682b22
$inversePrimary = 904a40
$secondary = ebbbb4
$onSecondary = 472824
$secondaryContainer = 603e39
$onSecondaryContainer = d8aaa3
$tertiary = d9c76e
$onTertiary = 393000
$tertiaryContainer = a1913f
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdad5
$primaryFixedDim = ffb4a8
$onPrimaryFixed = 3b0905
$onPrimaryFixedVariant = 73332b
$secondaryFixed = ffdad5
$secondaryFixedDim = ebbbb4
$onSecondaryFixed = 2e1410
$onSecondaryFixedVariant = 603e39
$tertiaryFixed = f6e387
$tertiaryFixedDim = d9c76e
$onTertiaryFixed = 211b00
$onTertiaryFixedVariant = 524700
$term0 = 353434
$term1 = ff5543
$term2 = ffbd9f
$term3 = ffdfd5
$term4 = b9ab66
$term5 = f18f8c
$term6 = ffba8f
$term7 = efd2c9
$term8 = b49e98
$term9 = ff8674
$term10 = ffd4c2
$term11 = fff1ed
$term12 = dcbc93
$term13 = ffa8a3
$term14 = ffd2b9
$term15 = ffffff
$rosewater = ffeeeb
$flamingo = ffd9d5
$pink = ffd2d2
$mauve = ffa8b3
$red = ff9791
$maroon = faaaa3
$peach = ffbeaf
$yellow = ffeee8
$green = ffd8c2
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbac8
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5c68
$kvisitedSelection = ce5c6a
$knegative = eb5447
$knegativeSelection = ec544a
$kneutral = ff896e
$kneutralSelection = ff8970
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = eedfdd
$subtext1 = d9c1be
$subtext0 = a18c89
$overlay2 = 8c7a77
$overlay1 = 776765
$overlay0 = 645654
$surface2 = 514644
$surface1 = 3f3534
$surface0 = 2b2322
$base = 181211
$mantle = 181211
$crust = 171110
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
