pragma Singleton
import QtQuick

// Generated by matugen - do not edit by hand.
// Source: ~/.config/matugen/templates/shell-palette.qml
// Named Colours, not Palette: QtQuick already defines a Palette type which shadows it.
//
// NOTE: Material You's "on<X>" roles are nested under `on` because QML parses any
// property literally named onFoo as a signal handler. Use Palette.on.primary etc.
QtObject {
    readonly property color background: "#1a1111"
    readonly property color surface: "#1a1111"
    readonly property color surfaceDim: "#1a1111"
    readonly property color surfaceBright: "#423736"
    readonly property color surfaceContainerLowest: "#140c0c"
    readonly property color surfaceContainerLow: "#231919"
    readonly property color surfaceContainer: "#271d1d"
    readonly property color surfaceContainerHigh: "#322827"
    readonly property color surfaceContainerHighest: "#3d3231"
    readonly property color surfaceVariant: "#534342"
    readonly property color inverseSurface: "#f1dedd"
    readonly property color outline: "#a08c8b"
    readonly property color outlineVariant: "#534342"
    readonly property color shadow: "#000000"
    readonly property color scrim: "#000000"
    readonly property color primary: "#ffb3ae"
    readonly property color primaryContainer: "#733330"
    readonly property color inversePrimary: "#904a46"
    readonly property color secondary: "#e7bdb9"
    readonly property color secondaryContainer: "#5d3f3d"
    readonly property color tertiary: "#e2c28c"
    readonly property color tertiaryContainer: "#594319"
    readonly property color error: "#ffb4ab"
    readonly property color errorContainer: "#93000a"

    // "content drawn on top of <role>"
    readonly property QtObject on: QtObject {
        readonly property color background: "#f1dedd"
        readonly property color surface: "#f1dedd"
        readonly property color surfaceVariant: "#d8c2c0"
        readonly property color inverseSurface: "#382e2d"
        readonly property color primary: "#571e1c"
        readonly property color primaryContainer: "#ffdad7"
        readonly property color secondary: "#442927"
        readonly property color secondaryContainer: "#ffdad7"
        readonly property color tertiary: "#402d04"
        readonly property color tertiaryContainer: "#ffdea7"
        readonly property color error: "#690005"
        readonly property color errorContainer: "#ffdad6"
    }
}
