pragma Singleton
import QtQuick

// Generated by matugen - do not edit by hand.
// Source: ~/.config/matugen/templates/shell-palette.qml
// Named Colours, not Palette: QtQuick already defines a Palette type which shadows it.
//
// NOTE: Material You's "on<X>" roles are nested under `on` because QML parses any
// property literally named onFoo as a signal handler. Use Palette.on.primary etc.
QtObject {
    readonly property color background: "#1a110f"
    readonly property color surface: "#1a110f"
    readonly property color surfaceDim: "#1a110f"
    readonly property color surfaceBright: "#423734"
    readonly property color surfaceContainerLowest: "#140c0a"
    readonly property color surfaceContainerLow: "#231917"
    readonly property color surfaceContainer: "#271d1b"
    readonly property color surfaceContainerHigh: "#322825"
    readonly property color surfaceContainerHighest: "#3d3230"
    readonly property color surfaceVariant: "#53433f"
    readonly property color inverseSurface: "#f1dfda"
    readonly property color outline: "#a08c88"
    readonly property color outlineVariant: "#53433f"
    readonly property color shadow: "#000000"
    readonly property color scrim: "#000000"
    readonly property color primary: "#ffb4a1"
    readonly property color primaryContainer: "#723524"
    readonly property color inversePrimary: "#8f4b39"
    readonly property color secondary: "#e7bdb3"
    readonly property color secondaryContainer: "#5d4038"
    readonly property color tertiary: "#dac58d"
    readonly property color tertiaryContainer: "#534519"
    readonly property color error: "#ffb4ab"
    readonly property color errorContainer: "#93000a"

    // "content drawn on top of <role>"
    readonly property QtObject on: QtObject {
        readonly property color background: "#f1dfda"
        readonly property color surface: "#f1dfda"
        readonly property color surfaceVariant: "#d8c2bc"
        readonly property color inverseSurface: "#392e2b"
        readonly property color primary: "#561f10"
        readonly property color primaryContainer: "#ffdbd2"
        readonly property color secondary: "#442a23"
        readonly property color secondaryContainer: "#ffdbd2"
        readonly property color tertiary: "#3b2f04"
        readonly property color tertiaryContainer: "#f7e1a6"
        readonly property color error: "#690005"
        readonly property color errorContainer: "#ffdad6"
    }
}
